.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bgeo_qt test_bgeo_qt
clean: FORCE
	$(MAKE) -C .. bgeo_qt_clean test_bgeo_qt_clean
check: FORCE
	$(MAKE) -C .. test_bgeo_qt_check
bgeo-qt bgeo-qt.exe: FORCE
	 $(MAKE) -C .. bgeo_qt
apk: FORCE
	$(MAKE) -C .. bgeo_qt_apk
